baseURL = 'https://ponnekanti.net/'
languageCode = 'en-gb'
title = "Manav's Weblog"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build.environment]
  HUGO_VERSION = "0.134.2"